apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod-with-config
  labels:
    app: webapp-config-example
spec:
  containers:
    - name: webapp
      image: nginxdemos/hello:plain-text
      ports:
        - containerPort: 80
      env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: ENV
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: PASSWORD
  restartPolicy: Never
